### ISSUE TITLE
Generator CLI: app generator looks for model in wrong directory

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Haulmont/jmix-frontend#197]
```
gen-jmix-front react-typescript:app --dest example-react-app --model scripts/model/projectModel-scr-jmix.json
```

will look for model in `example-react-app/scripts/model/projectModel-scr-jmix.json`

This is caused by obtaining a project model at `deriveTemplateModel` stage when `process.cwd()` points at destination directory rather than the directory the command was invoked from.

The project model should be obtained (either from Studio or from answers) at `getProjectModel` stage. `defaultGetProjectModel` should implement both scenarios correctly.

**Comment by karandashovrz** [comment]
@vyacheslav-pushkin 
Let me explain, what real happens here.

First of all, `deriveTemplateModel` is not the point. The log showing, that error was happened on Generate SDK stage.

![screen](https://user-images.githubusercontent.com/77386189/113666199-f64b9300-96bf-11eb-982f-e086686ce0e4.jpg)

`SDK Generator` uses `base-generator`, which has own `executeDir`, and when `SDK Generator` is started, its `exucetionDir` is different with `invocationDir` of `ReactTSAppGenerator`. This issue is observed, when model option contains relative path to project model json. As for the `deriveTemplate`, its has `process.cwd()` call, but its used to set directory for `projectModel` export of existing jmix project (if model was out in options but we have answers), so this code is safe.
I think,  we should keep `invocationDir` as generator property and set it in constructor (same approach implemented in `base-generator`).  If we keep it inside methods (especially asynchronous) it doesn't guarantee that value of `invocationDir` will be correct at  call moment.
